export const CartActionTypes = {
  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
  CART_CLEAR_ITEM: 'CART_CLEAR_ITEM',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
  FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS'
};
